language: python

sudo: false

matrix:
  fast_finish: true
  include:
  - python: 2.7
    env: TEST_TARGET=default
  - python: 3.4
    env: TEST_TARGET=default
  - python: 3.5
    env: TEST_TARGET=default
  - python: 3.5
    env: TEST_TARGET=coding_standards
  allow_failures:
  - python: 3.5
    env: TEST_TARGET=coding_standards

before_install:
    - wget http://bit.ly/miniconda -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --all --yes
    - conda config --add channels conda-forge -f
    - conda create --yes -n TEST python=$TRAVIS_PYTHON_VERSION --file requirements.txt --file requirements-dev.txt
    - source activate TEST
    - travis_retry conda install --yes pytest # GUI
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

# Test source distribution.
install:
    - python setup.py sdist && version=$(python setup.py --version) && pushd dist  && pip install ctd-${version}.tar.gz && popd

script:
    - if [[ $TEST_TARGET == 'default' ]]; then
        py.test -vv ;
      fi

    - if [[ $TEST_TARGET == 'coding_standards' ]]; then
        find . -type f -name "*.py" ! -name 'conf.py' | xargs flake8 --max-line-length=100 ;
      fi
